// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIO3KpdjBjjbvo0cxarvb1MsG3tfYLxk',
    appId: '1:802157028016:web:d7ebbd033b6be7a3741175',
    messagingSenderId: '802157028016',
    projectId: 'afetapp-b512d',
    authDomain: 'afetapp-b512d.firebaseapp.com',
    storageBucket: 'afetapp-b512d.firebasestorage.app',
    measurementId: 'G-MQKRMRXFRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl3gfNu0EVc-TxerXl6VcQ8B6L_50xccA',
    appId: '1:802157028016:android:0dab74f6792eb711741175',
    messagingSenderId: '802157028016',
    projectId: 'afetapp-b512d',
    storageBucket: 'afetapp-b512d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ8y7l_JBmrpERoCKxPiuGw5qDI1FCzqI',
    appId: '1:802157028016:ios:42fb28a10e530102741175',
    messagingSenderId: '802157028016',
    projectId: 'afetapp-b512d',
    storageBucket: 'afetapp-b512d.firebasestorage.app',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ8y7l_JBmrpERoCKxPiuGw5qDI1FCzqI',
    appId: '1:802157028016:ios:42fb28a10e530102741175',
    messagingSenderId: '802157028016',
    projectId: 'afetapp-b512d',
    storageBucket: 'afetapp-b512d.firebasestorage.app',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxIO3KpdjBjjbvo0cxarvb1MsG3tfYLxk',
    appId: '1:802157028016:web:0e56e1e44f0c4fd8741175',
    messagingSenderId: '802157028016',
    projectId: 'afetapp-b512d',
    authDomain: 'afetapp-b512d.firebaseapp.com',
    storageBucket: 'afetapp-b512d.firebasestorage.app',
    measurementId: 'G-2YX90MJG8S',
  );
}
